In [59]:
import pandas as pd
import numpy as np

In [60]:
df_disater = pd.read_csv('Total_Disasters_2024.csv')
df_deaths = pd.read_csv('Number_of_Deaths_2024.csv')
df_financal = pd.read_csv('Total_Financial_Damage_2024.csv')
df_injuries = pd.read_csv('Number_of_Injuries_2024.csv')

In [61]:
df_2019 = pd.read_csv('data_since_2019.csv')

In [62]:
df_2019

,State Name,State Code,Year,Total Deaths,No. Injured,Total Damage ('000 US$),Total Disasters,Disaster Types
0,Alabama,AL,2019,56.0,114.0,2925000.0,15.0,"{'Severe Storm': 13, 'Tornado': 2}"
1,Arkansas,AR,2019,13.0,12.0,4500000.0,39.0,{'Flood': 39}
2,California,CA,2019,76.0,14.0,1625000.0,61.0,"{'Fire': 21, 'Earthquake': 3, 'Severe Storm': 37}"
3,Colorado,CO,2019,27.0,57.0,0.0,0.0,0
4,Connecticut,CT,2019,2.0,12.0,1200000.0,0.0,0
...,...,...,...,...,...,...,...,...
238,Oregon,OR,2023,0.0,0.0,0.0,5.0,"{'Mud/Landslide': 1, 'Fire': 4}"
239,Rhode Island,RI,2023,0.0,0.0,0.0,1.0,{'Fire': 1}
240,South Carolina,SC,2023,0.0,0.0,0.0,1.0,{'Hurricane': 1}
241,South Dakota,SD,2023,0.0,0.0,0.0,23.0,"{'Flood': 1, 'Winter Storm': 22}"
242,Vermont,VT,2023,0.0,0.0,0.0,12.0,"{'Flood': 3, 'Severe Storm': 9}"

In [63]:
# Select only the columns we need 'State Code', 'Predicted Total Disasters for 2024'
# df_disater = df_disater[['State Code', 'Predicted Total Disasters for 2024']]

In [64]:
df_disater = df_disater.rename(columns={'Predicted Number of Total Disasters for 2024': 'Total Disasters'})
df_deaths = df_deaths.rename(columns={'Predicted Total Deaths for 2024':'Total Deaths'})
df_financal = df_financal.rename(columns={'Predicted Number of Financial Damage for 2024':'Total Damage (\'000 US$)'})
df_injuries = df_injuries.rename(columns={'Predicted Number of Injuries for 2024':'No. Injured'})

In [65]:
df_all = df_disater.merge(df_deaths, on='State Code', how='outer').merge(df_financal, on='State Code', how='outer').merge(df_injuries, on='State Code', how='left')

In [66]:
# set all nagative values in df_all to 0, except for "State Code" column
df_all[df_all.columns.difference(['State Code'])] = df_all[df_all.columns.difference(['State Code'])].clip(lower=0)

In [67]:
state_name_mapping = {
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'FL': 'Florida',
    'GA': 'Georgia',
    'IA': 'Iowa',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NJ': 'New Jersey',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'PA': 'Pennsylvania',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'DE': 'Delaware',
    'KY': 'Kentucky',
    'NH': 'New Hampshire',
    'NY': 'New York',
    'OR': 'Oregon',
    'AZ': 'Arizona',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'ME': 'Maine',
    'MT': 'Montana',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'UT': 'Utah',
    'VT': 'Vermont',
    'WY': 'Wyoming',
    'AK': 'Alaska',
    'MP': 'Northern Mariana Islands',
    'PR': 'Puerto Rico',
    'VI': 'Virgin Islands',
    'DC': 'District of Columbia',
    'RI': 'Rhode Island',
    'AS': 'American Samoa'
}

In [68]:
# Add State Name column, if State Code is not in the mapping, then the State Name will be Unknown
df_all['State Name'] = df_all['State Code'].map(state_name_mapping).fillna('Unknown')

In [69]:
df_all['Year'] = 2024

In [70]:
df_all

,State Code,Total Disasters,Total Deaths,Total Damage ('000 US$),No. Injured,State Name,Year
0,NY,19.0,96.0,2882742.0,50.0,New York,2024
1,TX,51.0,140.0,9765709.0,120.0,Texas,2024
2,DE,0.0,46.0,2542493.0,262.0,Delaware,2024
3,GA,27.0,82.0,4591511.0,80.0,Georgia,2024
4,OR,12.0,25.0,1530954.0,2.0,Oregon,2024
5,CO,2.0,41.0,3639014.0,9.0,Colorado,2024
6,AL,24.0,93.0,3742729.0,152.0,Alabama,2024
7,CA,74.0,58.0,5482422.0,0.0,California,2024
8,FL,81.0,468.0,42013286.0,124.0,Florida,2024
9,MS,20.0,103.0,4583559.0,88.0,Mississippi,2024
10,OH,9.0,80.0,4617743.0,92.0,Ohio,2024
11,LA,18.0,79.0,5388677.0,36.0,Louisiana,2024
12,PA,16.0,51.0,3568660.0,47.0,Pennsylvania,2024
13,IN,23.0,60.0,3629788.0,112.0,Indiana,2024
14,MN,31.0,45.0,1180960.0,3.0,Minnesota,2024
15,OK,25.0,54.0,6281580.0,87.0,Oklahoma,2024
16,TN,27.0,96.0,4396354.0,124.0,Tennessee,2024
17,WI,17.0,63.0,2865605.0,70.0,Wisconsin,2024
18,VA,48.0,123.0,12320691.0,149.0,Virginia,2024
19,IL,20.0,59.0,2936929.0,88.0,Illinois,2024
20,MT,12.0,4.0,322077.0,61.0,Montana,2024
21,NJ,10.0,29.0,39130.0,19.0,New Jersey,2024
22,SC,13.0,32.0,3396396.0,76.0,South Carolina,2024
23,WY,3.0,7.0,322135.0,22.0,Wyoming,2024
24,AR,15.0,53.0,5630438.0,106.0,Arkansas,2024
25,KY,52.0,78.0,4271106.0,38.0,Kentucky,2024
26,GU,2.0,-0.0,30.0,0.0,Guam,2024
27,WA,25.0,73.0,7297336.0,10.0,Washington,2024
28,UT,7.0,4.0,840650.0,5.0,Utah,2024
29,NV,3.0,47.0,6045539.0,16.0,Nevada,2024
30,WV,26.0,44.0,2433731.0,14.0,West Virginia,2024
31,NC,31.0,136.0,30783278.0,244.0,North Carolina,2024
32,CT,2.0,44.0,0.0,24.0,Connecticut,2024
33,NE,29.0,42.0,4449508.0,48.0,Nebraska,2024
34,AK,9.0,0.0,282303.0,0.0,Alaska,2024
35,ME,9.0,19.0,1954204.0,43.0,Maine,2024
36,KS,38.0,44.0,5346644.0,121.0,Kansas,2024
37,MO,36.0,113.0,3720614.0,125.0,Missouri,2024
38,MA,8.0,24.0,823246.0,8.0,Massachusetts,2024
39,RI,5.0,26.0,6210472.0,0.0,Rhode Island,2024
40,HI,3.0,1.0,0.0,0.0,Hawaii,2024
41,MI,9.0,20.0,3210257.0,43.0,Michigan,2024
42,SD,26.0,10.0,1170674.0,2.0,South Dakota,2024
43,ID,3.0,80.0,1646553.0,0.0,Idaho,2024
44,AZ,1.0,26.0,3572241.0,3.0,Arizona,2024
45,IA,29.0,37.0,3340639.0,71.0,Iowa,2024
46,MD,0.0,59.0,4301609.0,174.0,Maryland,2024
47,VT,8.0,18.0,2429997.0,0.0,Vermont,2024
48,NM,4.0,0.0,257761.0,0.0,New Mexico,2024
49,ND,32.0,7.0,1010359.0,12.0,North Dakota,2024
50,NH,7.0,14.0,780982.0,0.0,New Hampshire,2024
51,DC,1.0,19.0,1486900.0,1.0,District of Columbia,2024
52,MP,7.0,0.0,0.0,0.0,Northern Mariana Islands,2024
53,AS,3.0,0.0,0.0,0.0,American Samoa,2024
54,PR,177.0,0.0,0.0,0.0,Puerto Rico,2024
55,FM,3.0,0.0,0.0,0.0,Unknown,2024
56,VI,3.0,0.0,0.0,0.0,Virgin Islands,2024
57,MH,12.0,0.0,0.0,0.0,Unknown,2024
58,PW,1.0,0.0,0.0,0.0,Unknown,2024
59,Virgin Islands of the U.S.,2.0,0.0,0.0,0.0,Unknown,2024

In [71]:
'''
low-risk is < 17.5 deaths
Medium-risk is >17.5 and <77 deaths
High-risk is >=77 deaths
'''

# Add Risk Level column
df_all['Risk Level'] = np.where(df_all['Total Deaths'] < 17.5, 1, np.where(df_all['Total Deaths'] < 77, 2, 3))

In [72]:
df_all

,State Code,Total Disasters,Total Deaths,Total Damage ('000 US$),No. Injured,State Name,Year,Risk Level
0,NY,19.0,96.0,2882742.0,50.0,New York,2024,3
1,TX,51.0,140.0,9765709.0,120.0,Texas,2024,3
2,DE,0.0,46.0,2542493.0,262.0,Delaware,2024,2
3,GA,27.0,82.0,4591511.0,80.0,Georgia,2024,3
4,OR,12.0,25.0,1530954.0,2.0,Oregon,2024,2
5,CO,2.0,41.0,3639014.0,9.0,Colorado,2024,2
6,AL,24.0,93.0,3742729.0,152.0,Alabama,2024,3
7,CA,74.0,58.0,5482422.0,0.0,California,2024,2
8,FL,81.0,468.0,42013286.0,124.0,Florida,2024,3
9,MS,20.0,103.0,4583559.0,88.0,Mississippi,2024,3
10,OH,9.0,80.0,4617743.0,92.0,Ohio,2024,3
11,LA,18.0,79.0,5388677.0,36.0,Louisiana,2024,3
12,PA,16.0,51.0,3568660.0,47.0,Pennsylvania,2024,2
13,IN,23.0,60.0,3629788.0,112.0,Indiana,2024,2
14,MN,31.0,45.0,1180960.0,3.0,Minnesota,2024,2
15,OK,25.0,54.0,6281580.0,87.0,Oklahoma,2024,2
16,TN,27.0,96.0,4396354.0,124.0,Tennessee,2024,3
17,WI,17.0,63.0,2865605.0,70.0,Wisconsin,2024,2
18,VA,48.0,123.0,12320691.0,149.0,Virginia,2024,3
19,IL,20.0,59.0,2936929.0,88.0,Illinois,2024,2
20,MT,12.0,4.0,322077.0,61.0,Montana,2024,1
21,NJ,10.0,29.0,39130.0,19.0,New Jersey,2024,2
22,SC,13.0,32.0,3396396.0,76.0,South Carolina,2024,2
23,WY,3.0,7.0,322135.0,22.0,Wyoming,2024,1
24,AR,15.0,53.0,5630438.0,106.0,Arkansas,2024,2
25,KY,52.0,78.0,4271106.0,38.0,Kentucky,2024,3
26,GU,2.0,-0.0,30.0,0.0,Guam,2024,1
27,WA,25.0,73.0,7297336.0,10.0,Washington,2024,2
28,UT,7.0,4.0,840650.0,5.0,Utah,2024,1
29,NV,3.0,47.0,6045539.0,16.0,Nevada,2024,2
30,WV,26.0,44.0,2433731.0,14.0,West Virginia,2024,2
31,NC,31.0,136.0,30783278.0,244.0,North Carolina,2024,3
32,CT,2.0,44.0,0.0,24.0,Connecticut,2024,2
33,NE,29.0,42.0,4449508.0,48.0,Nebraska,2024,2
34,AK,9.0,0.0,282303.0,0.0,Alaska,2024,1
35,ME,9.0,19.0,1954204.0,43.0,Maine,2024,2
36,KS,38.0,44.0,5346644.0,121.0,Kansas,2024,2
37,MO,36.0,113.0,3720614.0,125.0,Missouri,2024,3
38,MA,8.0,24.0,823246.0,8.0,Massachusetts,2024,2
39,RI,5.0,26.0,6210472.0,0.0,Rhode Island,2024,2
40,HI,3.0,1.0,0.0,0.0,Hawaii,2024,1
41,MI,9.0,20.0,3210257.0,43.0,Michigan,2024,2
42,SD,26.0,10.0,1170674.0,2.0,South Dakota,2024,1
43,ID,3.0,80.0,1646553.0,0.0,Idaho,2024,3
44,AZ,1.0,26.0,3572241.0,3.0,Arizona,2024,2
45,IA,29.0,37.0,3340639.0,71.0,Iowa,2024,2
46,MD,0.0,59.0,4301609.0,174.0,Maryland,2024,2
47,VT,8.0,18.0,2429997.0,0.0,Vermont,2024,2
48,NM,4.0,0.0,257761.0,0.0,New Mexico,2024,1
49,ND,32.0,7.0,1010359.0,12.0,North Dakota,2024,1
50,NH,7.0,14.0,780982.0,0.0,New Hampshire,2024,1
51,DC,1.0,19.0,1486900.0,1.0,District of Columbia,2024,2
52,MP,7.0,0.0,0.0,0.0,Northern Mariana Islands,2024,1
53,AS,3.0,0.0,0.0,0.0,American Samoa,2024,1
54,PR,177.0,0.0,0.0,0.0,Puerto Rico,2024,1
55,FM,3.0,0.0,0.0,0.0,Unknown,2024,1
56,VI,3.0,0.0,0.0,0.0,Virgin Islands,2024,1
57,MH,12.0,0.0,0.0,0.0,Unknown,2024,1
58,PW,1.0,0.0,0.0,0.0,Unknown,2024,1
59,Virgin Islands of the U.S.,2.0,0.0,0.0,0.0,Unknown,2024,1

In [73]:
# df_all.to_csv('data_2024.csv', index=False)

Merging

In [74]:
df_2019.drop(columns=['Disaster Types'], inplace=True)

In [75]:
merged_df = pd.concat([df_2019, df_all], ignore_index=True)

In [76]:
merged_df

,State Name,State Code,Year,Total Deaths,No. Injured,Total Damage ('000 US$),Total Disasters,Risk Level
0,Alabama,AL,2019,56.0,114.0,2925000.0,15.0,NaN
1,Arkansas,AR,2019,13.0,12.0,4500000.0,39.0,NaN
2,California,CA,2019,76.0,14.0,1625000.0,61.0,NaN
3,Colorado,CO,2019,27.0,57.0,0.0,0.0,NaN
4,Connecticut,CT,2019,2.0,12.0,1200000.0,0.0,NaN
...,...,...,...,...,...,...,...,...
298,Unknown,FM,2024,0.0,0.0,0.0,3.0,1.0
299,Virgin Islands,VI,2024,0.0,0.0,0.0,3.0,1.0
300,Unknown,MH,2024,0.0,0.0,0.0,12.0,1.0
301,Unknown,PW,2024,0.0,0.0,0.0,1.0,1.0
302,Unknown,Virgin Islands of the U.S.,2024,0.0,0.0,0.0,2.0,1.0

In [78]:
merged_df.to_csv('merged.csv', index=False)